from langchain_openai import ChatOpenAI
from langchain_google_genai import GoogleGenerativeAI
import os
from dotenv import load_dotenv 
from langchain_core.runnables import RunnableSequence, RunnableLambda
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.messages import HumanMessage, SystemMessage, AIMessage
from langchain_core.output_parsers import StrOutputParser


# Check OpenAI API key is set
load_dotenv()  # Load environment variables from .env file

if os.getenv("OPENAI_API_KEY"):
    print("OpenAI API key is set.")
else:
    print("OpenAI API key is not set. Please set it in the .env file.")
    raise ValueError("OpenAI API key is not set. Please set it in the .env file.")


# Create first simple chain

# task 1: initiate the OpenAI LLM
llm_openai = ChatOpenAI(model="gpt-5.4-mini",temperature=0)

# task 2: define a chat prompt template
prompt_template = ChatPromptTemplate.from_messages([
    ("system", "You are an expert cook. Provide a recipe based on the main ingredient."),
    ("user", "{ingredient}") 
    ])

# task 3: Initialize output parser
output_parser = StrOutputParser()

# What output parser does is it takes the output from the LLM and converts it into a string format that we can easily work with in our code.
# This is especially useful when the LLM's response might be in a more complex format, and we want to ensure we have a clean string to work with for further processing or display.

# task 4: define a custom runnable to print the recipe in a formatted way
# make below function more readable and formatted

def custom_recipe(recipe: str) -> dict:
    print("Here is the recipe in a formatted way:")
    print("-" * 40)
    return {"recipe": recipe}

custom_recipe_runnable = RunnableLambda(custom_recipe)

# What above code line 38 to 44 does ?
# it defines a custom function called custom_recipe that takes a recipe as input, prints it in a formatted way, and returns a dictionary with the formatted recipe. 
# We then create a Runnablelambda from this function, which allows us to use it as a step in our chain.

# TASK - 5 [Template For Post]
prompt_post = ChatPromptTemplate.from_messages(
    messages=[
        ("system", "You're a social media post generator. "),
        ("human", "Create a post for the following text for Instagram: {recipe}"),
    ]
)


# taks 6: Genrate social media post from the recipe
llm_openai_post = ChatOpenAI(model="gpt-5.4-mini",temperature=0)

# Task 7 - Output parser for the post
output_parser_post = StrOutputParser()

# Create chain by combining the tasks using LECL operator
chain = prompt_template | llm_openai | output_parser | custom_recipe_runnable | prompt_post | llm_openai_post | output_parser_post

# task 8: invoke the chain with user input
response = chain.invoke(input={"ingredient": "Paneer", "recipe": "1. Marinate the Paneer with spices. 2. Heat oil in a pan and cook the Paneer until done. 3. Serve hot with rice or bread."})

print(response)


# What is the difference when we use custom runnable in the chain ?
# When we use a custom runnable in the chain, it allows us to perform additional processing or formatting on the output from the LLM before passing it to the next step in the chain.
# In this case, the custom_recipe_runnable takes the recipe generated by the LLM, prints it in a formatted way, and then returns it in a dictionary format that can be used as input for the next step in the chain (the prompt for generating a social media post).
